import { IMessage } from '@/features/messages/types'

export const messagesDummyData: IMessage[] = [
  {
    id: '1',
    content: 'Hey, are you free to talk later today?',
    isRead: true,
    isSent: true,
    sentDate: '2024-12-22T08:30:00Z',
  },
  {
    id: '2',
    content: 'Sure, I’m available after 3 PM. Let me know what works for you.',
    isRead: true,
    isSent: false,
    sentDate: '2024-12-22T08:35:00Z',
  },
  {
    id: '3',
    content: 'Great, let’s catch up at 4 PM.',
    isRead: true,
    isSent: true,
    sentDate: '2024-12-22T08:36:00Z',
  },
  {
    id: '4',
    content: 'Sounds good. See you then!',
    isRead: true,
    isSent: false,
    sentDate: '2024-12-22T08:40:00Z',
  },
  {
    id: '5',
    content: 'By the way, did you check out the new project brief?',
    isRead: true,
    isSent: true,
    sentDate: '2024-12-22T12:00:00Z',
  },
  {
    id: '6',
    content: 'Yes, I did. It looks promising, but there are a few details we should discuss.',
    isRead: true,
    isSent: false,
    sentDate: '2024-12-22T12:10:00Z',
  },
  {
    id: '7',
    content: 'Sure, let’s add it to our agenda for today’s call.',
    isRead: true,
    isSent: true,
    sentDate: '2024-12-22T12:15:00Z',
  },
  {
    id: '8',
    content: 'Perfect. I also have some updates about the marketing strategy.',
    isRead: true,
    isSent: false,
    sentDate: '2024-12-22T12:20:00Z',
  },
  {
    id: '9',
    content: 'Hey, quick question. Do you remember the deadline for the client deliverable?',
    isRead: false,
    isSent: true,
    sentDate: '2024-12-23T09:00:00Z',
  },
  {
    id: '10',
    content: 'I think it’s January 5th, but I’ll double-check and let you know.',
    isRead: false,
    isSent: false,
    sentDate: '2024-12-23T09:05:00Z',
  },
  {
    id: '11',
    content: 'Got it, thanks!',
    isRead: false,
    isSent: true,
    sentDate: '2024-12-23T09:10:00Z',
  },
  {
    id: '12',
    content: 'Hey, I just got confirmation about the team meeting tomorrow. It’s at 10 AM.',
    isRead: true,
    isSent: false,
    sentDate: '2024-12-23T10:00:00Z',
  },
  {
    id: '13',
    content: 'Thanks for the update! I’ll be there.',
    isRead: true,
    isSent: true,
    sentDate: '2024-12-23T10:05:00Z',
  },
  {
    id: '14',
    content: 'Also, don’t forget to bring the presentation slides. We’ll need them for the discussion.',
    isRead: true,
    isSent: false,
    sentDate: '2024-12-23T10:07:00Z',
  },
  {
    id: '15',
    content: 'Of course! I’m finalizing them right now.',
    isRead: true,
    isSent: true,
    sentDate: '2024-12-23T10:10:00Z',
  },
  {
    id: '16',
    content: 'Great. By the way, did you see the new report from the analytics team? It’s very detailed, and it gives us some great insights into customer behavior. We should incorporate it into our plans.',
    isRead: true,
    isSent: false,
    sentDate: '2024-12-23T10:15:00Z',
  },
  {
    id: '17',
    content: 'Yes, I reviewed it last night. The data on customer retention is especially interesting. Let’s discuss it in tomorrow’s meeting.',
    isRead: true,
    isSent: true,
    sentDate: '2024-12-23T10:20:00Z',
  },
  {
    id: '18',
    content: 'Sounds like a plan!',
    isRead: true,
    isSent: false,
    sentDate: '2024-12-23T10:25:00Z',
  },
  {
    id: '19',
    content: 'Quick heads-up: the client might ask for an update on the website redesign. Are we ready with that?',
    isRead: true,
    isSent: false,
    sentDate: '2024-12-23T11:00:00Z',
  },
  {
    id: '20',
    content: 'Almost! The team is wrapping up the final testing phase. We should be good to present it by Friday.',
    isRead: true,
    isSent: true,
    sentDate: '2024-12-23T11:10:00Z',
  },
]
