# Generated by Django 4.2.10 on 2025-01-10 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('zoom_id', models.CharField(max_length=255)),
                ('encrypted_password', models.CharField(max_length=255)),
                ('join_url', models.CharField(max_length=255)),
                ('booked_users', models.ManyToManyField(blank=True, related_name='booked_sessions', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
